#include "lang_autogen.h"

// THIS FILE WAS AUTO-GENERATED.
char *internalEnglish[LANG_STR_COUNT] = {
    "English (internal)",
    "Save Changes",
    "Back",
    "Network Settings",
    "Advanced Options",
    "<no values>",
    "Settings saved to %s",
    "Error writing settings!",
    "Exit",
    "Settings",
    "Menu",
    "BDM Games",
    "HDD Games",
    "ETH Games",
    "Apps",
    "Theme",
    "Language",
    "The system will be powered off.",
    "Exit to Browser?",
    "Cancel updating?",
    "%d: HardDisk Drive not detected.",
    "%d: HardDisk Drive not formatted.",
    "%d: Network startup error.",
    "%d: No network adaptor detected.",
    "%d: Cannot connect to SMB server.",
    "%d: Cannot log into SMB server.",
    "%d: Cannot open SMB share.",
    "%d: Cannot list SMB shares.",
    "%d: Cannot list games.",
    "%d: DHCP server unavailable.",
    "%d: No network connection.",
    "On",
    "Off",
    "OK",
    "Select",
    "Cancel",
    "Circle",
    "Cross",
    "Games List",
    "Game Settings",
    "Remove Settings",
    "Scrolling Speed",
    "Slow",
    "Medium",
    "Fast",
    "Default Menu",
    "Load From Disc",
    "Please wait.",
    "Error while loading the Game ID.",
    "Sort Games Alphabetically",
    "Error loading the language file.",
    "Debug Colors",
    "No controller detected, waiting...",
    "Cover Art",
    "Widescreen",
    "Power Off",
    "Loading config...",
    "Saving config...",
    "Start Device",
    "Refresh",
    "BDM Start Mode",
    "HDD (APA) Start Mode",
    "ETH Start Mode",
    "Applications Start Mode",
    "Auto",
    "Manual",
    "Start NBD Server",
    "NBD Server starting...",
    "NBD Server running...",
    "Failed to start NBD Server.",
    "NBD Server unloading...",
    "IGR Path",
    "Background Color",
    "Text Color",
    "- SMB Server -",
    "IP Address Type",
    "Static",
    "DHCP",
    "IP Address",
    "Address",
    "Mask",
    "Gateway",
    "DNS Server",
    "Port",
    "Share",
    "User",
    "Password",
    "<not set>",
    "Address Type",
    "IP",
    "NetBIOS",
    "Accept",
    "Item will be permanently deleted, continue?",
    "Rename",
    "Delete",
    "Run",
    "Display Settings",
    "Write Operations",
    "Remember Last Played Game",
    "Select Button",
    "Error, the game is fragmented.",
    "Error, could not run the item.",
    "Test Changes",
    "Leave empty for GUEST auth.",
    "Accurate Reads",
    "Synchronous Mode",
    "Unhook Syscalls",
    "Skip Videos",
    "Emulate DVD-DL",
    "Disable IGR",
    "Changing the size will reformat the VMC.",
    "Create",
    "Start",
    "Modify",
    "Abort",
    "Reset",
    "Use Generic",
    "Configure VMC",
    "Name",
    "Size",
    "Status",
    "Progress",
    "VMC file exists.",
    "Invalid VMC file, size is incorrect.",
    "VMC file needs to be created.",
    "Error accessing VMC %s. Continue with the Memory Card in slot %d?",
    "Automatic Refresh",
    "About",
    "Coders",
    "Quality Assurance",
    "BDM Prefix Path",
    "Boots a custom ELF after an IGR. Keep it on the memory card (mc0:/mc1:) -- the post-reset loader can't reach MMCE; for MMCE, chain through an MC loader like PS2BBL.",
    "Value in minute(s), 0 to disable spin down.",
    "Automatic HDD Spin Down",
    "Video Mode",
    "Dialog Color",
    "Selected Color",
    "Reset Colors",
    "Info",
    "Custom ELF",
    "Color Selection",
    "Reconnect",
    "Leave empty to list shares.",
    "ETH Prefix Path",
    "Backspace",
    "Space",
    "Enter",
    "Mode",
    "VMC Slot 1",
    "VMC Slot 2",
    "Game ID",
    "DMA Mode",
    "V-Sync",
    "Mode 1",
    "Mode 2",
    "Mode 3",
    "Mode 4",
    "Mode 5",
    "Mode 6",
    "Configure GSM",
    "Ethernet Link Mode",
    "100Mbit Full-duplex",
    "100Mbit Half-duplex",
    "10Mbit Full-duplex",
    "10Mbit Half-duplex",
    "GSM Settings",
    "GSM Selector",
    "Toggles GSM on/off.",
    "Forced custom display mode.",
    "H-POS",
    "Horizontal adjustment.",
    "V-POS",
    "Vertical adjustment.",
    "Overscan",
    "Overscan adjustment.",
    "FMV Skip",
    "Skips full motion videos.",
    "Cheat Settings",
    "PS2RD Cheat Engine",
    "Lets PS2RD Cheat Engine patch your game.",
    "PS2RD Cheat Engine Mode",
    "Auto select or select game cheats.",
    "Auto Select Cheats",
    "Select Game Cheats",
    "Error: failed to load cheat file.",
    "No cheats found.",
    "Download Defaults",
    "Network Update",
    "Overwrite Existing Records",
    "Update failed.",
    "Failed to connect to update server.",
    "Update completed.",
    "Update cancelled.",
    "Download settings from the network?",
    "Customized Settings",
    "Downloaded Defaults",
    "Auto start in %i s...",
    "Auto Start",
    "Value in second(s), 0 to disable auto start.",
    "PS2 Logo",
    "Displayed for a valid disc logo matching the console's region.",
    "Controller Emulation",
    "Pad Emulator Settings",
    "Pad Emulator",
    "Turns on/off Pad Emulator for selected game.",
    "Pad Emulator Mode",
    "Select Pad Emulator mode.",
    "DualShock3/4 USB",
    "DualShock3/4 BT",
    "Settings For Port:",
    "Select Pad Emulator port for settings.",
    "Emulation",
    "Turns on/off Pad Emulator for selected port.",
    "Vibration",
    "Turns on/off vibration for Pad Emulator selected port.",
    "USB Bluetooth Adapter MAC Address:",
    "DS Controller Paired To MAC Address:",
    "Pair",
    "Pair DS Controller",
    "Pair DS controller with Bluetooth adapter MAC address.",
    "Not Connected",
    "Bluetooth Adapter Information",
    "Shows more information and supported features.",
    "HCI Version:",
    "LMP Version:",
    "Manufacturer ID:",
    "Supported Features:",
    "Yes",
    "No",
    "Bluetooth adapter should be fully compatible with DS3/DS4 controllers.",
    "Bluetooth adapter may not work correctly with DS3/DS4 controllers.",
    "Multitap Emulation",
    "Turns on/off Multitap emulation for selected game.",
    "Multitap Emulator On Port:",
    "Select port for Multitap emulation.",
    "Fake DS3 Workaround",
    "Some fake DS3s need a workaround, this option will enable it.",
    "Emulate FIELD Flipping",
    "Fix for games that glitch under progressive video modes.",
    "Parental Lock Settings",
    "Parental Lock Password",
    "Leave blank to disable the parental lock.",
    "Enter Parental Lock Password",
    "Parental lock password incorrect.",
    "Parental lock disabled.",
    "Build Options:",
    "Error - this password cannot be used.",
    "VMC %s file is fragmented. Continue with Memory Card in slot %d?",
    "Audio Settings",
    "Sound Effects",
    "Boot Sound",
    "Sound Effects Volume",
    "Boot Sound Volume",
    "Confirm video mode change?",
    "Cache Game List (HDD)",
    "Notifications",
    "Config loaded from %s",
    "Theme loaded from %s",
    "Language loaded from %s",
    "%s partition mounted.",
    "Options",
    "Game settings saved.",
    "%s settings removed.",
    "Overwrites existing game compatibility settings when enabled.",
    "Settings Mode",
    "Global",
    "Per Game",
    "All",
    "Select settings to remove.",
    "Support Forums:",
    "Title",
    "Genre",
    "Release",
    "Developer",
    "Description",
    "BDM Devices",
    "Controller Settings",
    "Turn on/off Block Device Manager.",
    "Turn on/off BDM Devices (USB/MX4SIO/ILINK/HDD).",
    "USB Games",
    "iLink Games",
    "MX4SIO Games",
    "Controller Macros",
    "Pad Macro Settings",
    "Pad macros",
    "Analog Slow-Down:",
    "Reduce the range of analog stick when button is pressed.",
    "Left Stick",
    "Right Stick",
    "Analog Axis Invert:",
    "Inverts the axis of selected analog stick.",
    "Turbo Button Speed",
    "How fast the button is pressed when turbo is active.",
    "While Button Pressed",
    "Toggled By Button",
    "JAPANESE",
    "ENGLISH",
    "FRENCH",
    "SPANISH",
    "GERMAN",
    "ITALIAN",
    "DUTCH",
    "PORTUGUESE",
    "RUSSIAN",
    "KOREAN",
    "TRADITIONAL CHINESE",
    "SIMPLIFIED CHINESE",
    "OSD Settings",
    "OSD Language",
    "Force a custom language configuration",
    "Enable",
    "Screen Size",
    "Full Screen",
    "Video Mode",
    "System Default",
    "Background Music",
    "Background Music Volume",
    "Default Theme Music",
    "Set path to stream music for internal theme.",
    "High",
    "Low",
    "Analog X-Axis Sensitivity",
    "Analog Y-Axis Sensitivity",
    "Files found: %i",
    "Cheat Selection",
    "Only one HDD allowed, enabling locks APA or GPT.",
    "Could not write settings to %s (error %d)",
    "Launch PS2 Disc",
    "No PS2 disc in the drive.",
    "Financial Support",
    "Default",
    "Loading settings...",
    "Ready.",
    "Favourites",
    "Favourites Start Mode",
    "Favourite",
    "%s not allowed through Favourites Menu.",
    "%s is not allowed while the item is marked as favourite.",
    "Advanced Arguments",
    "Advanced",
    "Artwork Settings",
    "VCD BDMA Apply on Launch",
    "BDMA Mode",
    "BDMA Settings",
    "BDMA Source",
    "Colors",
    "Communication Settings",
    "Controller Emulation",
    "Controller Macros",
    "Loader Core",
    "Animation Speed",
    "Cover Count",
    "Dim Side Covers",
    "Center Scale",
    "Coverflow Settings",
    "Default Loader Core",
    "Display",
    "PS2RD Cheat Image",
    "Cover Art .tar Archive",
    "Browse Folders in Game List",
    "Game Launching",
    "Game List Settings",
    "Game Sources",
    "On: auto-equip the launched VCD's matching exFAT driver to the memory card before boot (recommended). Off: manage it yourself with the BDMA Source/Mode pickers below.",
    "exFAT block-device driver POPSTARTER loads. Changing it copies the modules to the card; FAT32 = none (built-in driver).",
    "Device whose POPS folder holds your BDMAssault driver files (usbd.irx.* / usbhdfsd.irx.*).",
    "Global default core for games whose per-game Loader Core is set to Default. <OPL> is the native core; Neutrino chains the external neutrino.elf. A per-game choice always overrides this.",
    "Apply a prebuilt PS2RD .img patch to your game.",
    "Show subfolders of CD/DVD as browsable entries; select to open, cancel to go back",
    "Switch to bootcard cmd will be sent to the selected slot(s) on IGR",
    "OFF may help performance but can cause MMCE timeouts to result in freezes",
    "Lower values may improve performance but result in instabilities",
    "Neutrino only -- fix games that overrun an IOP buffer (-gc=7)",
    "Extra Neutrino flags, space-separated (e.g. -mt=dvd). Global applies to all games; per-game adds on top. Prefix a flag with $ to disable it without deleting.",
    "Force Neutrino's block-device filesystem (-bsdfs). Auto = per-device default. hdl/bd are expert options; pair them with a matching -dvd= in the launch args if the auto path shape doesn't fit.",
    "Device holding neutrino.elf (in a NEUTRINO/ or neutrino/ folder). Auto = the game's own device then mc0/mc1. Game's Device = the game's device only.",
    "Field-flipping fix for games that shake or tear under a forced Neutrino Video mode. Needs a Neutrino Video mode set.",
    "Force Neutrino's GS output video mode (-gsm). Off keeps the game's default.",
    "Device holding POPS/POPSTARTER.ELF for PS1 VCD launches. Default = boot device (cwd) then the VCD's own device. Game's Device = the VCD's device only. Custom reveals a free-text path.",
    "Custom POPSTARTER.ELF path; quietly falls back to the device POPS folder if blank/missing. Keyboard caps at 31 chars; longer paths via settings_riptopl.cfg.",
    "Render optical barcode for Pixel FX / RetroGEM / PS2Digital on PS1 VCD launch",
    "Copy OPL's own Network Settings values (above) into these POPStarter fields. Nothing is written until you confirm with OK.",
    "SMB port on the server -- 445 is the default. Leave at 0 (or 445) for a normal share; use 139 for older SMB1 servers.",
    "Short vibration when moving the cursor, confirming or going back -- needs a DualShock in analog mode",
    "Show only Disc 1 of a multi-disc PS1 game in the device lists (POPSLoader style). Hides files named (Disc 2), (CD 2), etc. All discs stay on the card for in-game swapping; Favourites are not filtered.",
    "Cosmetic only -- hide a leading game-ID prefix (e.g. SLUS_005.51.) from PS1/VCD list names. Names without an ID are shown as-is. Does not change launch, cover art, or favourites.",
    "Launch without this slot's VMC while keeping its card configured. Neutrino launches only; the game then uses the real card in that slot.",
    "Interface",
    "Network",
    "MMCE",
    "IGR Bootcard Slot(s)",
    "MMCE Start Mode",
    "MMCE Prefix Path",
    "MMCE Slot",
    "Use timeout alarms",
    "Wait cycles after /ACK low",
    "Mode 7",
    "ATA0 Image (-ata0)",
    "ATA0 ID (-ata0id)",
    "ATA1 Image (-ata1)",
    "Auto: -bsd -dvd -gc -gsm -mc -dbc -logo",
    "Config (-cfg)",
    "Working Dir (-cwd)",
    "Debug Colors (-dbc)",
    "Boot ELF (-elf)",
    "Extra Args",
    "PS2 Logo (-logo)",
    "Quick Boot (-qb)",
    "Network Protocol",
    "Neutrino Launch Args",
    "Neutrino Filesystem",
    "Neutrino Defaults",
    "Neutrino Device",
    "Neutrino GSM Compatibility",
    "Neutrino Video",
    "OSD Defaults",
    "Path Prefixes",
    "Path Settings",
    "Plasma Blend Color",
    "POPStarter",
    "POPSTARTER.ELF Device",
    "POPSTARTER.ELF Path",
    "RetroGEM Game ID",
    "Import POPSLoader Settings",
    "No existing POPStarter SMB configuration was detected. Enter the correct network settings before creating one.",
    "POPStarter SMB Network",
    "Controller Vibration in Menus",
    "Security",
    "Storage and Cache",
    "Tools",
    "First disc only (multi-disc PS1)",
    "Hide PS1 Game ID (VCD list)",
    "exFAT",
    "fat32",
    "fat32 is recommended for non exFAT USB users.",
    "fat32 or exFAT USB Mode?",
    "USB VCD Mode",
    "Disable VMC 1 (keep card)",
    "Disable VMC 2 (keep card)",
    "None",
    "Small",
    "Large",
    "Normal",
    "Controller",
    "Audio",
    "Neutrino cannot launch from this device -- launch aborted.",
    "Neutrino network config (bsd toml) missing or unwritable -- launch aborted, check the neutrino folder.",
    "Per-game VMC file not found -- launching without it (game uses its real card).",
    "Game's Device",
    "Neutrino does not support this file format, launching with <OPL> core",
    "Neutrino ELF not found, launching with <OPL> core",
    "Too fragmented for Neutrino (%d fragments, limit %d incl. VMCs) -- trying the OPL core instead.",
    "BDMA module files not found on the source device.",
    "Not enough memory card space for the BDMA modules.",
    "Error writing the BDMA modules to the memory card.",
    "UDPBD needs a static PS2 IP. Set one in Network Config (DHCP is currently on).",
    "Restart OPL to apply the network boot protocol change.",
    "UDPFS on -- open the new UDPFS tab and press Confirm to connect. PC side runs udpfsd -fsroot <games folder>.",
    "Network block device on -- its tab appears once the PC server answers (udpfsd -bdpath for UDPFS Image, udpbd-server for UDPBD).",
    "Too fragmented for Neutrino (%d fragments, limit %d incl. VMCs) -- defragment on the PC; launch aborted.",
    "UDPFS Games",
    "Network (UDP) games can only boot via the Neutrino core. Check that neutrino.elf is present and the format is supported.",
    "PS1 (.VCD) games can't be launched over the network device.",
    "MX4SIO and pad emulation share the SIO2 bus and the game may fail to boot.",
    "MMCE card switch not confirmed -- launching anyway",
    "UDPFSBD Games",
    "UDPBD Games",
    "Loading storage drivers...",
    "Loading USB storage driver...",
    "Missing POPSTARTER.ELF",
    "Missing POPSTARTER SMB requirements",
    "SMB games have no Neutrino support -- launching with the OPL core.",
    "Neutrino cannot use a VMC on APA HDD (no pfs support) -- launching without it.",
    "VCD",
    "Showing VCD games",
    "Showing disc games",
    "Scanning USB / card / network drives...",
    "Starting network...",
    "Scanning HDD...",
    "USB",
    "MX4SIO",
    "MMCE",
    "Internal HDD",
    "USB (FAT32)",
    "USB (exFAT)",
    "MX4SIO (exFAT)",
    "MMCE (exFAT)",
    "HDD (exFAT)",
    "Loaded from %s",
    "Couldn't write POPSTARTER network config to the memory card.",
    "This setting is not used with the Neutrino core.",
    "Disable All",
    "Loading theme sounds...",
    "Building menu...",
    "WARNING -- forcing 1080p is experimental and unverified. It may show no picture or, on some hardware, stress the console. Proceed at your own risk.",
    "Proceed with forcing 1080p for this game?",
    "Are you sure? This applies the experimental 1080p mode to this game.",
    "Custom Settings Path",
    "Save settings to a folder you choose, e.g. mass0:/OPL. Leave blank to use the folder OPL booted from. The device is loaded on demand, so it need not be mounted when you type it.",
    "Per Game + Global",
    "GSM Defaults (All Games)",
    "Device busy: the settings write never started. Try again once loading finishes.",
    "No memory card found -- settings cannot be saved. OPL was booted from a network device, whose settings must live on a local card.",
    "Preparing PS1 driver on memory card...",
    "USB BDMA Driver",
    "PS1 (VCD) launches from a USB stick only. The PS2 cannot detect whether a stick is fat32 or exFAT, so POPSTARTER's driver must be chosen. Ask prompts on every USB VCD launch; exFAT or fat32 pin the answer and skip the prompt.",
    "Ask",
    "HDD settings used the safe fallback home: %s",
    "General Settings",
    "Device Settings",
    "MMCE Games",
    "Advanced",
    "MMCE Settings",
    "Lock Sema Enqueuing Method",
    "THFIFO may help with compatibility but worsen performance",
    "Write POPSTARTER Network Config",
    "Also save these IP + SMB share values to POPSTARTER's own IPCONFIG.DAT / SMBCONFIG.DAT on the memory card (for VCD-over-SMB).",
    "Neutrino ELF Path",
    "Full path to neutrino.elf (e.g. mc0:NEUTRINO/neutrino.elf). Blank = auto-detect on mc0/mc1.",
    "Scanning memory cards...",
    "Arming MMCE game-ID...",
    "UDPFS Access",
    "MMCE GameID not applied -- neutrino.elf is on this card (switching it would unload Neutrino).",
    "APA and exFAT internal HDD were both enabled -- one was disabled automatically (check Device Settings).",
    "VCD Settings",
};
